version: '3'

services:

  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
#    entrypoint: docker-entrypoint.sh
    command: node ./node/index.js
    networks:
      - node-network  
    volumes:
      - .:/usr/src/app/
      # the volume above prevents our host system's node_modules to be mounted
      - exclude:/usr/src/app/node_modules/
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - db
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    restart: always
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
    exclude: